name: Normal Run
on:
  workflow_dispatch:
permissions:
    contents: write
env:
  NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
  ###### Configs :
  JAVA_VERSION: 20
  # Backup to be repeated every few seconds?
  BACKUP_TIME: 300
  # How much RAM should be given to the game server? (Enter value in Gigabyte)
  SERVER_RAM: 4

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install JavaJDK
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: ${{ env.JAVA_VERSION }}
      - run: java -version

      - name: Install & Authenticate NGROK
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && echo "deb https://ngrok-agent.s3.amazonaws.com/ buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list && sudo apt update && sudo apt install ngrok
          ngrok authtoken $NGROK_AUTH_TOKEN

      - name: Run The Server
        run:  |
          (ngrok tcp 25565) &
          (while true; do git config --global user.email github-actions@github.com && git config --global user.name github-actions && git add . && git commit -m "Upload New Files" && git push -f; sleep $BACKUP_TIME; done) &
          java -Xmx${{ env.SERVER_RAM }}G -jar server.jar

      - name: Login To Github And Push Final Backup
        if: always()
        run: |
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
          git add .
          git commit -m "Upload New Files"
          git push -f
