# This is a basic workflow to help you get started with Actions

name: testx

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env: 
  ###### Web Console Settings
  # ** this area only for plugin based server softwares (like papermc, purpurmc, spigot and ...)
  # ** please set it to disable if you are using vannila or mod based server software
  WEB_CONSOLE_INSTALL: 'enable'
  WEB_CONSOLE_USERNAME: 'MyAdmin'
  WEB_CONSOLE_PASSWORD: 'MyPass'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install WebConsole If It Enabled
        run: |
          if [[ "${{ env.WEB_CONSOLE_INSTALL }}" == "enable" ]]; then
            mkdir plugins
            cd plugins
            wget -o https://code.midline.ir/github-mcserver/addons/web-console/WebConsole.jar
            mkdir WebConsole
            wget -o https://code.midline.ir/github-mcserver/addons/web-console/config.yml
            awk '{gsub("OpUserX", "$WEB_CONSOLE_USERNAME"); print}' config.yml
            awk '{gsub("OpPassX", "$WEB_CONSOLE_PASSWORD"); print}' config.yml
            cd ../..
          else
            echo "Skipping Install WebConsole"
          fi

        
